const searchQueries = [
  "Ale",
  "Almond butter",
  "Almond milk",
  "Almonds",
  "Apple juice",
  "Apple pie",
  "Apples",
  "Apricot jam",
  "Asparagus",
  "Avocados",
  "Bacon",
  "Bagels",
  "Baguette",
  "Banana loaf",
  "Bananas",
  "Beans",
  "Beef burger",
  "Beef curry",
  "Beef meatballs",
  "Beef mince",
  "Beef noodles",
  "Beef steak",
  "Beer",
  "Beetroot",
  "Biscuits",
  "Blue cheese",
  "Brazil nuts",
  "Bread",
  "Breakfast cereal",
  "Brie",
  "Broccoli",
  "Butter",
  "Cabbage",
  "Caesar salad",
  "Camembert",
  "Carrot cake",
  "Carrots",
  "Cashew nuts",
  "Cauliflower",
  "Cereal bars",
  "Cheddar cheese",
  "Cheesecake",
  "Cherry tomatoes",
  "Chia seeds",
  "Chicken breast",
  "Chicken burger",
  "Chicken curry",
  "Chicken noodles",
  "Chicken pasta",
  "Chicken sausages",
  "Chicken thighs",
  "Chicken wings",
  "Chickpeas",
  "Chilli con carne",
  "Chocolate biscuits",
  "Chocolate cake",
  "Chocolate cereals",
  "Chocolate cheesecake",
  "Chocolate spread",
  "Cider",
  "Coconut milk",
  "Coconut oil",
  "Cod",
  "Cod fish fingers",
  "Cod fishcakes",
  "Coffee beans",
  "Coffee pods",
  "Cookies",
  "Cottage cheese",
  "Cottage pie",
  "Courgettes",
  "Couscous",
  "Cow's milk",
  "Cracker biscuits",
  "Crisps",
  "Croissants",
  "Cucumber",
  "Dairy-free cheese",
  "Dairy-free ice cream",
  "Dark chocolate",
  "Doughnuts",
  "Egg noodles",
  "Eggs",
  "Falafels",
  "Feta cheese",
  "Flapjack",
  "Frozen chips (french fries)",
  "Frozen jacket potatoes",
  "Frozen mashed potato",
  "Frozen onion rings",
  "Frozen potato wedges",
  "Frozen roast potatoes",
  "Frozen sweet potato fries",
  "Fruit cake",
  "Fruit smoothies",
  "Garden peas",
  "Goat's cheese",
  "Granola",
  "Grapes",
  "Haddock risotto",
  "Halloumi cheese",
  "Ice cream",
  "Ice lollies",
  "Instant coffee",
  "Kale",
  "Kiwis",
  "Lamb (leg)",
  "Lamb Hotpot",
  "Lamb burgers",
  "Lamb casserole",
  "Lamb chops",
  "Lamb curry",
  "Lamb moussaka",
  "Lasagne sheets",
  "Lemons",
  "Lentils",
  "Lettuce",
  "Limes",
  "Macaroni cheese",
  "Mackerel",
  "Marmalade",
  "Meat pizza",
  "Meat-free burger",
  "Meat-free mince",
  "Meat-free nuggets",
  "Meat-free sausages",
  "Melon",
  "Milk chocolate",
  "Mixed salad",
  "Mozzarella cheese",
  "Muesli",
  "Muffins",
  "Mushrooms",
  "Naan",
  "Nut loaf",
  "Oat milk",
  "Olive oil",
  "Onions",
  "Orange juice",
  "Oranges",
  "Pain au chocolat",
  "Pancakes",
  "Parmesan cheese",
  "Parsnips",
  "Pasta shells",
  "Peanut butter",
  "Peanuts",
  "Pears",
  "Pecan nuts",
  "Penne pasta",
  "Peppers",
  "Pineapple",
  "Pitta bread",
  "Popcorn",
  "Poppadoms",
  "Pork chops",
  "Pork loin",
  "Pork sausage rolls",
  "Pork sausages",
  "Porridge (oatmeal)",
  "Potato croquettes",
  "Potatoes",
  "Prawn crackers",
  "Prawns",
  "Protein bar",
  "Protein shake",
  "Pumpkin seeds",
  "Quiche",
  "Quinoa",
  "Rapeseed oil",
  "Raspberries",
  "Raspberry jam",
  "Rice",
  "Rice milk",
  "Rice noodles",
  "Ricotta cheese",
  "Salmon",
  "Salmon fishcakes",
  "Sausage rolls",
  "Shepherd’s pie",
  "Shortbread biscuits",
  "Sourdough bread",
  "Soy desert",
  "Soy milk",
  "Soy yoghurt",
  "Spaghetti",
  "Spaghetti bolognese",
  "Spinach",
  "Sponge cake",
  "Steak pie",
  "Strawberries",
  "Strawberry jam",
  "Sugar",
  "Sunflower oil",
  "Sunflower seeds",
  "Sweetcorn",
  "Tea",
  "Tofu",
  "Tomato ketchup",
  "Tomatoes",
  "Tortilla wraps",
  "Tuna",
  "Vegan pizza",
  "Vegetable lasagne",
  "Vegetarian chilli con carne",
  "Vegetarian curry",
  "Vegetarian pizza",
  "Walnuts",
  "Watermelon",
  "Wine",
  "Yoghurt",
];

export default searchQueries;